In [1]:
import pandas as pd
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

### Load Kundenpünktlichkeit file

In [2]:
sbb_kundenpunktlichkeit_url = "https://data.sbb.ch/explore/dataset/kundenpunktlichkeit-tag/download/?format=csv&refine.datum=2021&timezone=Europe/Berlin&lang=de&use_labels_for_header=true&csv_separator=%3B"
sbb_kundenpunktlichkeit = pd.read_csv(sbb_kundenpunktlichkeit_url, sep=";")
sbb_kundenpunktlichkeit.head()

,Datum,Region,Kundenpünktlichkeit KPP,KPP FV,KPP RV,KAP,KAP FV,KAP RV,ZPK,ZPK FV,ZPK RV,KCOR,cor,Schlüssel
0,2021-05-25,RSD,94.918495,95.426320,94.395315,95.139686,95.696075,94.641082,90.933092,94.236842,89.363288,96.100573,98.857404,2021-05-25 00:00:00-RSD
1,2021-08-02,NETZ,94.188074,91.856371,95.646505,95.032295,93.046989,96.154779,92.431867,90.794310,92.722489,97.387402,98.984799,2021-08-02 00:00:00-NETZ
2,2021-12-06,ROT,95.898679,92.144273,97.188118,96.513592,92.614831,97.679774,94.693909,93.436806,94.822609,97.438887,99.218330,2021-12-06 00:00:00-ROT
3,2021-12-07,RWT,82.369407,80.749471,84.463777,84.619555,83.599801,85.852916,82.543177,84.012107,82.123871,96.986279,98.268975,2021-12-07 00:00:00-RWT
4,2021-12-08,RME,78.908769,74.327699,83.553592,79.959805,75.739123,83.855013,81.506110,80.190429,81.797692,93.130670,97.346103,2021-12-08 00:00:00-RME

### Clean Data

In [3]:
sbb_kundenpunktlichkeit.drop(columns=['Kundenpünktlichkeit KPP', 'KPP FV', 'KPP RV', 'KAP',
                                      'KAP FV', 'KAP FV', 'KAP RV', 'KCOR', 'cor', 'Schlüssel'], inplace=True)
sbb_kundenpunktlichkeit.head()

        Datum Region        ZPK     ZPK FV     ZPK RV
0  2021-05-25    RSD  90.933092  94.236842  89.363288
1  2021-08-02   NETZ  92.431867  90.794310  92.722489
2  2021-12-06    ROT  94.693909  93.436806  94.822609
3  2021-12-07    RWT  82.543177  84.012107  82.123871
4  2021-12-08    RME  81.506110  80.190429  81.797692

In [4]:
sbb_kundenpunktlichkeit.columns = ['date', 'sbbregion_key', 'zugpuenktlichkeit', 'zugpuenktlichkeit_fv', 'zugpuenktlichkeit_rv']

In [10]:
## convert date to expected format
def round_value(value):
    return round(value,10)
sbb_kundenpunktlichkeit['zugpuenktlichkeit']= sbb_kundenpunktlichkeit['zugpuenktlichkeit'].apply(round_value)
sbb_kundenpunktlichkeit['zugpuenktlichkeit_fv']= sbb_kundenpunktlichkeit['zugpuenktlichkeit_fv'].apply(round_value)
sbb_kundenpunktlichkeit['zugpuenktlichkeit_rv']= sbb_kundenpunktlichkeit['zugpuenktlichkeit_rv'].apply(round_value)

In [8]:
sbb_kundenpunktlichkeit.sort_values(by=['date', 'sbbregion_key'] , inplace=True)
sbb_kundenpunktlichkeit.head()

,date,sbbregion_key,zugpuenktlichkeit,zugpuenktlichkeit_fv,zugpuenktlichkeit_rv
1544,2021-01-01,NETZ,96.811215,96.811215,96.811215
917,2021-01-01,RME,97.080340,97.080340,97.080340
918,2021-01-01,ROT,98.099171,98.099171,98.099171
1545,2021-01-01,RSD,95.470488,95.470488,95.470488
1546,2021-01-01,RWT,94.018834,94.018834,94.018834

### Export to csv

In [9]:
sbb_kundenpunktlichkeit.to_csv( "sbb_kundenpunktlichkeit_data.csv", index=False, encoding='utf-8-sig', line_terminator='\n')